# Generated by Django 6.0.5 on 2026-09-20 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


LEGACY_CATEGORY_LABELS = {
    'ROOMS': 'Rooms & Venues',
    'HARDWARE': 'IT & Hardware',
    'VEHICLES': 'Vehicles',
    'AV': 'Audio / Visual',
    'LAB': 'Laboratory & Equipment',
    'GENERAL': 'General Office Assets',
}


def migrate_legacy_resource_categories(apps, schema_editor):
    Resource = apps.get_model('resources', 'Resource')
    ResourceCategory = apps.get_model('resources', 'ResourceCategory')

    categories = {}
    for code, label in LEGACY_CATEGORY_LABELS.items():
        category, _ = ResourceCategory.objects.get_or_create(name=label)
        categories[code] = category

    for resource in Resource.objects.all():
        legacy_value = (getattr(resource, 'legacy_category', '') or 'GENERAL').strip()
        category = categories.get(legacy_value)
        if category is None:
            category, _ = ResourceCategory.objects.get_or_create(name=legacy_value or LEGACY_CATEGORY_LABELS['GENERAL'])
        resource.category = category
        resource.save(update_fields=['category'])


def restore_legacy_resource_categories(apps, schema_editor):
    Resource = apps.get_model('resources', 'Resource')
    for resource in Resource.objects.select_related('category').all():
        if resource.category:
            reverse_code = next(
                (code for code, label in LEGACY_CATEGORY_LABELS.items() if label == resource.category.name),
                resource.category.name,
            )
            resource.legacy_category = reverse_code
            resource.save(update_fields=['legacy_category'])


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_readable_table_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='category',
            new_name='legacy_category',
        ),
        migrations.AddField(
            model_name='resource',
            name='assigned_room',
            field=models.ForeignKey(blank=True, help_text='Optional room or venue this resource belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_resources', to='resources.resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_id',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_resource_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Resource categories',
                'db_table': 'resource_categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resources.resourcecategory'),
        ),
        migrations.RunPython(migrate_legacy_resource_categories, restore_legacy_resource_categories),
        migrations.RemoveField(
            model_name='resource',
            name='legacy_category',
        ),
    ]
