# Generated by Django 6.0.5 on 2026-09-21 22:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resource_assigned_room_resource_resource_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['resource_id', 'name']},
        ),
        migrations.AddField(
            model_name='resource',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged'), ('UNDER_REPAIR', 'Under Repair')], default='GOOD', max_length=30),
        ),
        migrations.AddField(
            model_name='resource',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_portable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Assigned room name or physical location', max_length=150),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ResourceInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_condition', models.CharField(blank=True, default='', max_length=30)),
                ('current_condition', models.CharField(max_length=30)),
                ('inspection_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='resources.resource')),
            ],
            options={
                'db_table': 'resource_inspections',
                'ordering': ['-inspection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_location', models.CharField(blank=True, default='', max_length=150)),
                ('new_location', models.CharField(max_length=150)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='resources.resource')),
            ],
            options={
                'db_table': 'resource_location_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
