# Generated by Django 6.0.5 on 2026-10-01 20:15

import django.db.models.deletion
import resources.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_allocation_created_at_allocation_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceReportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=resources.models.resource_report_ref, editable=False, max_length=24, unique=True)),
                ('report_type', models.CharField(choices=[('RESOURCE_REGISTER', 'Resource Register')], default='RESOURCE_REGISTER', max_length=40)),
                ('report_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel (.xlsx)'), ('CSV', 'CSV (.csv)')], default='PDF', max_length=10)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('response_notes', models.TextField(blank=True, default='')),
                ('generated_report', models.FileField(blank=True, null=True, upload_to='resource_reports/%Y/%m/')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_resource_report_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource_report_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resource_report_requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
