# Generated by Django 6.0.5 on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_financialsummaryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
