# Generated by Codex on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_expense_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgettransaction',
            name='action_type',
            field=models.CharField(
                choices=[
                    ('TOP_UP', 'Funds Added'),
                    ('DEDUCTION', 'Expense Approved'),
                    ('REJECTION', 'Expense Rejected'),
                    ('REFUND', 'Expense Reversal'),
                ],
                max_length=30,
            ),
        ),
    ]
