# Generated by Codex on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_budgettransaction_refund_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsummaryrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialsummaryrequest',
            name='report_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialsummaryrequest',
            name='report_format',
            field=models.CharField(default='PDF', max_length=10),
        ),
        migrations.AddField(
            model_name='financialsummaryrequest',
            name='report_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
