# Generated by Django 6.0.5 on 2026-09-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_budget_options_alter_budgettransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialsummaryrequest',
            name='report_format',
            field=models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel (.xlsx)')], default='PDF', max_length=10),
        ),
    ]
