# Generated by Django 6.0.5 on 2026-09-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_financialsummaryrequest_report_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialsummaryrequest',
            name='report_format',
            field=models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel (.xlsx)'), ('CSV', 'CSV (.csv)')], default='PDF', max_length=10),
        ),
    ]
