# Generated by Django 6.0.5 on 2026-10-01 16:37

import django.core.validators
import django.db.models.deletion
import finance.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_financialsummaryrequest_report_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsummaryrequest',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_summary_requests', to='finance.budget'),
        ),
        migrations.AddField(
            model_name='financialsummaryrequest',
            name='transaction_type',
            field=models.CharField(blank=True, default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='budgettransaction',
            name='action_type',
            field=models.CharField(choices=[('TOP_UP', 'Funds Added'), ('ALLOCATION', 'Income Allocation'), ('DEDUCTION', 'Expense Approved'), ('REFUND', 'Expense Reversal'), ('ADJUSTMENT', 'Controlled Adjustment'), ('REJECTION', 'Legacy Rejection Event')], max_length=30),
        ),
        migrations.CreateModel(
            name='DepartmentalIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=finance.models.income_ref, editable=False, max_length=24, unique=True)),
                ('source_name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unallocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date_received', models.DateField()),
                ('external_reference', models.CharField(blank=True, default='', max_length=120)),
                ('allocation_status', models.CharField(choices=[('UNALLOCATED', 'Unallocated'), ('PARTIALLY_ALLOCATED', 'Partially Allocated'), ('ALLOCATED', 'Allocated')], default='UNALLOCATED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departmental_income_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'departmental_income',
                'ordering': ['-date_received', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentalIncomeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=finance.models.income_allocation_ref, editable=False, max_length=24, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('allocated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departmental_income_allocations', to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_allocations', to='finance.budget')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.departmentalincome')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_allocation', to='finance.budgettransaction')),
            ],
            options={
                'db_table': 'departmental_income_allocations',
                'ordering': ['-allocated_at', '-id'],
            },
        ),
    ]
