import csv
import io
from datetime import date, datetime
from decimal import Decimal
from io import BytesIO

from django.utils import timezone
from django.utils.dateparse import parse_date

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, KeepTogether

import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter


def _money(value):
    return f"ZMW {Decimal(value or 0):,.2f}"


def _format_date(d):
    if not d:
        return "-"
    if isinstance(d, str):
        parsed = parse_date(d)
        if parsed:
            d = parsed
        else:
            return d
    if isinstance(d, (date, datetime)):
        return d.strftime("%d %B %Y")
    return str(d)


def _format_datetime(dt):
    if not dt:
        return "-"
    if isinstance(dt, datetime):
        return dt.strftime("%d %B %Y, %H:%M")
    return str(dt)


def _report_filename(file_format, start=None, end=None, reference=None):
    fmt = str(file_format).upper()
    if fmt in ("EXCEL", "XLSX"):
        ext = "xlsx"
        prefix = "DMS_Financial_Statement"
    elif fmt == "CSV":
        ext = "csv"
        prefix = "DMS_Financial_Ledger"
    else:
        ext = "pdf"
        prefix = "DMS_Financial_Statement"

    start_part = str(start) if start else "beginning"
    end_part = str(end) if end else "today"
    return f"{prefix}_{start_part}_to_{end_part}.{ext}"


class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_footer(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_page_footer(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))
        self.setStrokeColor(colors.HexColor("#cbd5e1"))
        self.setLineWidth(0.5)
        # Landscape A4 dimensions: 841.89 pt x 595.27 pt
        self.line(28, 30, 841.89 - 28, 30)
        ref = getattr(self, "report_ref", "-")
        left_text = f"System-generated by the Departmental Management System (DMS)  |  Reference: {ref}"
        self.drawString(28, 18, left_text)
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(841.89 - 28, 18, page_str)
        self.restoreState()


def _render_report_pdf(report):
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(A4),
        rightMargin=28,
        leftMargin=28,
        topMargin=26,
        bottomMargin=36,
    )

    styles = getSampleStyleSheet()

    # Typography styles
    inst_title_style = ParagraphStyle(
        "InstTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=16,
        textColor=colors.HexColor("#0b1338"),
    )
    dept_style = ParagraphStyle(
        "DeptTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10,
        leading=13,
        textColor=colors.HexColor("#334155"),
    )
    sys_style = ParagraphStyle(
        "SysTitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#64748b"),
    )
    doc_banner_style = ParagraphStyle(
        "DocBanner",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=15,
        textColor=colors.HexColor("#ea580c"),
    )
    meta_label_style = ParagraphStyle(
        "MetaLabel",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=7.5,
        leading=10,
        textColor=colors.HexColor("#475569"),
    )
    meta_val_style = ParagraphStyle(
        "MetaVal",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#0f172a"),
    )
    section_heading = ParagraphStyle(
        "SectionHeading",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10,
        leading=13,
        textColor=colors.HexColor("#0b1338"),
    )
    desc_style = ParagraphStyle(
        "LedgerDesc",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=7,
        leading=9,
        textColor=colors.HexColor("#1e293b"),
    )
    summary_p_style = ParagraphStyle(
        "StatementSummary",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=12,
        textColor=colors.HexColor("#1e293b"),
    )

    s = report["summary"]
    p = report.get("period", {})
    start_date = p.get("start")
    end_date = p.get("end") or date.today()
    start_str = _format_date(start_date)
    end_str = _format_date(end_date)
    period_display = f"{start_str} - {end_str}"
    ref_display = report.get("reference") or "FR-OFFICIAL"
    gen_time_str = _format_datetime(report.get("generated_at") or timezone.localtime(timezone.now()))

    story = []

    # 1. Institutional Header
    header_table_data = [
        [
            Paragraph("THE UNIVERSITY OF ZAMBIA", inst_title_style),
            Paragraph("FINANCIAL STATEMENT", doc_banner_style),
        ],
        [
            Paragraph("Department Of Computing & Informatics", dept_style),
            Paragraph(f"<b>Reference:</b> {ref_display}", meta_val_style),
        ],
        [
            Paragraph("Departmental Management System", sys_style),
            Paragraph(f"<b>Currency:</b> ZMW", meta_val_style),
        ],
    ]
    header_table = Table(header_table_data, colWidths=[520, 265])
    header_table.setStyle(
        TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("ALIGN", (1, 0), (1, -1), "RIGHT"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
            ("TOPPADDING", (0, 0), (-1, -1), 1),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ])
    )
    story.append(header_table)
    story.append(Spacer(1, 8))

    # 2. Metadata Block Table
    meta_table_data = [
        [
            Paragraph("<b>Reporting Period:</b>", meta_label_style),
            Paragraph(period_display, meta_val_style),
            Paragraph("<b>Generated:</b>", meta_label_style),
            Paragraph(gen_time_str, meta_val_style),
        ],
        [
            Paragraph("<b>Report Reference:</b>", meta_label_style),
            Paragraph(ref_display, meta_val_style),
            Paragraph("<b>Currency:</b>", meta_label_style),
            Paragraph("ZMW (Zambian Kwacha)", meta_val_style),
        ],
    ]
    meta_table = Table(meta_table_data, colWidths=[110, 270, 110, 295])
    meta_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ])
    )
    story.append(meta_table)
    story.append(Spacer(1, 10))

    # 3. Compact Financial Summary Table (Section 6)
    story.append(Paragraph("Financial Position Summary", section_heading))
    story.append(Spacer(1, 4))

    fin_pos_data = [
        ["Financial Position", "As At / Period", "Amount (ZMW)"],
        ["Opening Balance", f"As at {start_str}", _money(s["opening_balance"])],
        ["Funds Added", f"{start_str} - {end_str}", _money(s["funds_added"])],
        ["Approved / Accrued Expenditure", f"{start_str} - {end_str}", _money(s["approved_expenditure"])],
        ["Refunds / Reversals", f"{start_str} - {end_str}", _money(s["refunds"])],
        ["Adjustments", f"{start_str} - {end_str}", _money(s["adjustments"])],
        ["Net Movement", f"{start_str} - {end_str}", _money(s["net_movement"])],
        ["Closing Balance", f"As at {end_str}", _money(s["closing_balance"])],
    ]

    fin_table = Table(fin_pos_data, colWidths=[285, 320, 180])
    fin_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0b1338")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 8),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 4),
            ("TOPPADDING", (0, 0), (-1, 0), 4),
            # Opening Balance row styling
            ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
            ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#f8fafc")),
            # Net Movement row
            ("FONTNAME", (0, 6), (-1, 6), "Helvetica-Bold"),
            # Closing Balance row styling
            ("BACKGROUND", (0, 7), (-1, 7), colors.HexColor("#f1f5f9")),
            ("FONTNAME", (0, 7), (-1, 7), "Helvetica-Bold"),
            # Alignments & borders
            ("ALIGN", (2, 0), (2, -1), "RIGHT"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("FONTSIZE", (0, 1), (-1, -1), 7.5),
            ("TOPPADDING", (0, 1), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 1), (-1, -1), 3),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ])
    )
    story.append(fin_table)
    story.append(Spacer(1, 12))

    # 4. Detailed Ledger Transactions Table (Section 7)
    story.append(Paragraph("Detailed Ledger Transactions", section_heading))
    story.append(Spacer(1, 4))

    ledger_header = ["Date", "Reference", "Description", "Budget", "Debit (ZMW)", "Credit (ZMW)", "Before (ZMW)", "After (ZMW)"]
    ledger_rows = [ledger_header]

    for idx, r in enumerate(report.get("statement", [])):
        desc_cell = Paragraph(r.get("description") or "-", desc_style)
        debit_str = _money(r["debit"]) if r.get("debit") else "-"
        credit_str = _money(r["credit"]) if r.get("credit") else "-"
        before_str = _money(r.get("balance_before", 0))
        after_str = _money(r.get("balance_after", 0))

        ledger_rows.append([
            str(r.get("date")),
            r.get("reference") or "-",
            desc_cell,
            r.get("budget") or "-",
            debit_str,
            credit_str,
            before_str,
            after_str,
        ])

    if len(ledger_rows) == 1:
        ledger_rows.append(["-", "-", Paragraph("No financial transactions occurred within the specified reporting period.", desc_style), "-", "-", "-", _money(s["opening_balance"]), _money(s["closing_balance"])])

    ledger_table = Table(ledger_rows, repeatRows=1, colWidths=[65, 78, 222, 95, 80, 80, 85, 80])
    ledger_style = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0b1338")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 7.5),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#cbd5e1")),
        ("FONTSIZE", (0, 1), (-1, -1), 6.8),
        ("ALIGN", (4, 1), (-1, -1), "RIGHT"),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
    ]

    for i in range(1, len(ledger_rows)):
        if i % 2 == 0:
            ledger_style.append(("BACKGROUND", (0, i), (-1, i), colors.HexColor("#f8fafc")))

    ledger_table.setStyle(TableStyle(ledger_style))
    story.append(ledger_table)
    story.append(Spacer(1, 10))

    # 5. Statement Summary Paragraph (Section 8)
    summary_text = (
        f"<b>Statement Summary:</b> During the reporting period ({period_display}), funds added amounted to "
        f"<b>{_money(s['funds_added'])}</b> and approved/accrued expenditure amounted to "
        f"<b>{_money(s['approved_expenditure'])}</b>. "
        f"The closing balance as at <b>{end_str}</b> was <b>{_money(s['closing_balance'])}</b>."
    )
    story.append(KeepTogether([
        Paragraph(summary_text, summary_p_style),
        Spacer(1, 6)
    ]))

    def make_canvas(*args, **kwargs):
        c = NumberedCanvas(*args, **kwargs)
        c.report_ref = ref_display
        return c

    doc.build(story, canvasmaker=make_canvas)
    return buffer.getvalue()


def _render_report_excel(report):
    wb = openpyxl.Workbook()

    navy_fill = PatternFill(start_color="0B1338", end_color="0B1338", fill_type="solid")
    alt_fill = PatternFill(start_color="F8FAFC", end_color="F8FAFC", fill_type="solid")
    soft_fill = PatternFill(start_color="F1F5F9", end_color="F1F5F9", fill_type="solid")
    thin_border_side = Side(style="thin", color="CBD5E1")
    grid_border = Border(left=thin_border_side, right=thin_border_side, top=thin_border_side, bottom=thin_border_side)

    font_inst = Font(name="Calibri", size=13, bold=True, color="0B1338")
    font_dept = Font(name="Calibri", size=11, bold=True, color="334155")
    font_sys = Font(name="Calibri", size=9.5, italic=True, color="64748B")
    font_banner = Font(name="Calibri", size=12, bold=True, color="EA580C")
    font_section = Font(name="Calibri", size=11, bold=True, color="0B1338")
    font_header = Font(name="Calibri", size=9.5, bold=True, color="FFFFFF")
    font_bold = Font(name="Calibri", size=9.5, bold=True, color="0F172A")
    font_normal = Font(name="Calibri", size=9.5, color="0F172A")
    font_muted = Font(name="Calibri", size=9, color="475569")

    s = report["summary"]
    p = report.get("period", {})
    start_date = p.get("start")
    end_date = p.get("end") or date.today()
    start_str = _format_date(start_date)
    end_str = _format_date(end_date)
    period_display = f"{start_str} - {end_str}"
    ref_display = report.get("reference") or "FR-OFFICIAL"
    gen_time_str = _format_datetime(report.get("generated_at") or timezone.localtime(timezone.now()))

    # SHEET 1: Financial Statement
    ws1 = wb.active
    ws1.title = "Financial Statement"
    ws1.views.sheetView[0].showGridLines = True

    ws1["A1"] = "THE UNIVERSITY OF ZAMBIA"
    ws1["A1"].font = font_inst
    ws1["A2"] = "Department Of Computing & Informatics"
    ws1["A2"].font = font_dept
    ws1["A3"] = "Departmental Management System"
    ws1["A3"].font = font_sys
    ws1["A4"] = "FINANCIAL STATEMENT"
    ws1["A4"].font = font_banner

    ws1["A6"] = "Reporting Period:"
    ws1["A6"].font = font_muted
    ws1["B6"] = period_display
    ws1["B6"].font = font_bold

    ws1["A7"] = "Report Reference:"
    ws1["A7"].font = font_muted
    ws1["B7"] = ref_display
    ws1["B7"].font = font_bold

    ws1["A8"] = "Generated:"
    ws1["A8"].font = font_muted
    ws1["B8"] = gen_time_str
    ws1["B8"].font = font_normal

    ws1["A9"] = "Currency:"
    ws1["A9"].font = font_muted
    ws1["B9"] = "ZMW (Zambian Kwacha)"
    ws1["B9"].font = font_bold

    ws1["A11"] = "Financial Position Summary"
    ws1["A11"].font = font_section

    sum_headers = ["Financial Position", "As At / Period", "Amount (ZMW)"]
    for col_idx, text in enumerate(sum_headers, start=1):
        cell = ws1.cell(row=12, column=col_idx, value=text)
        cell.font = font_header
        cell.fill = navy_fill
        cell.alignment = Alignment(horizontal="left" if col_idx < 3 else "right", vertical="center")
        cell.border = grid_border

    summary_rows = [
        ("Opening Balance", f"As at {start_str}", float(s["opening_balance"]), True),
        ("Funds Added", f"{start_str} - {end_str}", float(s["funds_added"]), False),
        ("Approved / Accrued Expenditure", f"{start_str} - {end_str}", float(s["approved_expenditure"]), False),
        ("Refunds / Reversals", f"{start_str} - {end_str}", float(s["refunds"]), False),
        ("Adjustments", f"{start_str} - {end_str}", float(s["adjustments"]), False),
        ("Net Movement", f"{start_str} - {end_str}", float(s["net_movement"]), True),
        ("Closing Balance", f"As at {end_str}", float(s["closing_balance"]), True),
    ]

    for r_idx, (pos, prd, val, is_bold) in enumerate(summary_rows, start=13):
        c1 = ws1.cell(row=r_idx, column=1, value=pos)
        c2 = ws1.cell(row=r_idx, column=2, value=prd)
        c3 = ws1.cell(row=r_idx, column=3, value=val)

        c1.font = font_bold if is_bold else font_normal
        c2.font = font_normal
        c3.font = font_bold if is_bold else font_normal
        c3.number_format = "#,##0.00"
        c3.alignment = Alignment(horizontal="right")

        if pos == "Opening Balance":
            c1.fill = c2.fill = c3.fill = alt_fill
        elif pos == "Closing Balance":
            c1.fill = c2.fill = c3.fill = soft_fill

        c1.border = c2.border = c3.border = grid_border

    ws1["A22"] = "Statement Summary"
    ws1["A22"].font = font_section

    summary_note = (
        f"During the reporting period ({period_display}), funds added amounted to ZMW {float(s['funds_added']):,.2f} "
        f"and approved/accrued expenditure amounted to ZMW {float(s['approved_expenditure']):,.2f}. "
        f"The closing balance as at {end_str} was ZMW {float(s['closing_balance']):,.2f}."
    )
    ws1["A23"] = summary_note
    ws1["A23"].font = font_normal

    ws1.column_dimensions["A"].width = 34
    ws1.column_dimensions["B"].width = 32
    ws1.column_dimensions["C"].width = 22

    # SHEET 2: Detailed Ledger
    ws2 = wb.create_sheet(title="Detailed Ledger")
    ws2.views.sheetView[0].showGridLines = True

    ledger_headers = [
        "Date",
        "Reference",
        "Description",
        "Budget Category",
        "Action Type",
        "Debit (ZMW)",
        "Credit (ZMW)",
        "Balance Before (ZMW)",
        "Balance After (ZMW)",
        "Performed By",
    ]

    for col_idx, h_text in enumerate(ledger_headers, start=1):
        c = ws2.cell(row=1, column=col_idx, value=h_text)
        c.font = font_header
        c.fill = navy_fill
        c.alignment = Alignment(horizontal="right" if "ZMW" in h_text else "left", vertical="center")
        c.border = grid_border

    for row_idx, r in enumerate(report.get("statement", []), start=2):
        row_fill = alt_fill if row_idx % 2 == 1 else PatternFill(fill_type=None)

        cells = [
            ws2.cell(row=row_idx, column=1, value=str(r.get("date"))),
            ws2.cell(row=row_idx, column=2, value=r.get("reference") or "-"),
            ws2.cell(row=row_idx, column=3, value=r.get("description") or "-"),
            ws2.cell(row=row_idx, column=4, value=r.get("budget") or "Unassigned"),
            ws2.cell(row=row_idx, column=5, value=r.get("type") or "-"),
            ws2.cell(row=row_idx, column=6, value=float(r.get("debit") or 0)),
            ws2.cell(row=row_idx, column=7, value=float(r.get("credit") or 0)),
            ws2.cell(row=row_idx, column=8, value=float(r.get("balance_before") or 0)),
            ws2.cell(row=row_idx, column=9, value=float(r.get("balance_after") or 0)),
            ws2.cell(row=row_idx, column=10, value=r.get("performed_by") or "System"),
        ]

        for idx, cell in enumerate(cells):
            cell.font = font_normal
            cell.border = grid_border
            if row_fill.fill_type:
                cell.fill = row_fill
            if idx in (5, 6, 7, 8):
                cell.number_format = "#,##0.00"
                cell.alignment = Alignment(horizontal="right")

    ws2.freeze_panes = "A2"
    ws2.auto_filter.ref = ws2.dimensions

    col_widths = {
        "A": 14,
        "B": 18,
        "C": 38,
        "D": 22,
        "E": 16,
        "F": 16,
        "G": 16,
        "H": 20,
        "I": 20,
        "J": 18,
    }
    for col_letter, width in col_widths.items():
        ws2.column_dimensions[col_letter].width = width

    out_buffer = BytesIO()
    wb.save(out_buffer)
    return out_buffer.getvalue()


def _render_report_csv(report):
    """
    Exports detailed ledger transactions in a clean tabular CSV format.
    Suitable for pandas, Jupyter, Excel import, Power BI, and data analysis.
    """
    type_display_map = {
        "TOP_UP": "Top Up",
        "DEDUCTION": "Deduction",
        "REFUND": "Reversal",
        "ADJUSTMENT": "Adjustment",
        "REJECTION": "Rejection",
    }

    output = io.StringIO()
    writer = csv.writer(output, quoting=csv.QUOTE_MINIMAL)

    # Header row
    headers = [
        "Date",
        "Reference",
        "Budget",
        "Description",
        "Transaction Type",
        "Debit",
        "Credit",
        "Balance Before",
        "Balance After",
        "Performed By",
    ]
    writer.writerow(headers)

    for r in report.get("statement", []):
        tx_type_raw = r.get("type") or ""
        tx_type = type_display_map.get(tx_type_raw, tx_type_raw.replace("_", " ").title())
        debit_val = float(r.get("debit") or 0)
        credit_val = float(r.get("credit") or 0)
        before_val = float(r.get("balance_before") or 0)
        after_val = float(r.get("balance_after") or 0)

        writer.writerow([
            str(r.get("date") or ""),
            r.get("reference") or "",
            r.get("budget") or "Unassigned",
            r.get("description") or "",
            tx_type,
            f"{debit_val:.2f}",
            f"{credit_val:.2f}",
            f"{before_val:.2f}",
            f"{after_val:.2f}",
            r.get("performed_by") or "System",
        ])

    return output.getvalue().encode("utf-8-sig")


def _render_report_file(report, file_format):
    fmt = str(file_format).upper()
    if fmt in ("EXCEL", "XLSX"):
        return (
            _render_report_excel(report),
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )
    elif fmt == "CSV":
        return (
            _render_report_csv(report),
            "text/csv; charset=utf-8",
        )
    return (_render_report_pdf(report), "application/pdf")
