# Generated by Django 6.0.5 on 2026-09-20 23:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_readable_table_name'),
        ('users', '0003_usergroupcategory_alter_user_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='google_calendar_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='include_all_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='participant_categories',
            field=models.ManyToManyField(blank=True, related_name='activities', to='users.usergroupcategory'),
        ),
        migrations.AddField(
            model_name='activity',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='activities_to_attend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='reminder_minutes_before',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='activity',
            name='send_email_reminders',
            field=models.BooleanField(default=True),
        ),
    ]
