# Generated by Django 6.0.5 on 2026-09-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_google_calendar_link_and_more'),
        ('users', '0005_notification_recipientgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('MEETING', 'Departmental Meeting'), ('WORKSHOP', 'Workshop / Training'), ('SEMINAR', 'Academic Seminar'), ('ASSEMBLY', 'Departmental Assembly'), ('EXAM', 'Exam / Assessment'), ('OTHER', 'General Activity')], default='MEETING', max_length=40),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='external_participants',
            field=models.TextField(blank=True, default='', help_text='Comma/semicolon/newline-separated emails'),
        ),
        migrations.AddField(
            model_name='activity',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='activity',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='activity',
            name='recipient_groups',
            field=models.ManyToManyField(blank=True, related_name='activities', to='users.recipientgroup'),
        ),
        migrations.AddField(
            model_name='activity',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RESCHEDULED', 'Rescheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=30),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
