# Generated by Django 6.0.5 on 2026-10-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_activity_approval_status_activity_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='meeting_link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='activity',
            name='meeting_mode',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('ONLINE', 'Online'), ('HYBRID', 'Hybrid')], default='PHYSICAL', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='meeting_platform',
            field=models.CharField(blank=True, choices=[('', 'None'), ('GOOGLE_MEET', 'Google Meet'), ('ZOOM', 'Zoom'), ('MICROSOFT_TEAMS', 'Microsoft Teams'), ('OTHER', 'Other')], default='', max_length=30),
        ),
    ]
