# Generated by Django 6.0.5 on 2026-08-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('ROOMS', 'Rooms & Venues'), ('HARDWARE', 'IT & Hardware'), ('VEHICLES', 'Vehicles'), ('AV', 'Audio / Visual'), ('LAB', 'Laboratory & Equipment'), ('GENERAL', 'General Office Assets')], default='GENERAL', max_length=20),
        ),
    ]
