# Generated by Codex on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usergroupcategory_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_finance_balance_access',
            field=models.BooleanField(default=False),
        ),
    ]
