# Generated by Django 6.0.5 on 2026-09-21 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_has_finance_balance_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('GENERAL', 'General Notification'), ('ACTIVITY_INVITE', 'Activity Invitation'), ('ACTIVITY_UPDATE', 'Activity Update'), ('ACTIVITY_CANCEL', 'Activity Cancelled'), ('EXPENSE_SUBMITTED', 'Expense Submitted'), ('EXPENSE_APPROVED', 'Expense Approved'), ('EXPENSE_REJECTED', 'Expense Rejected'), ('REPORT_READY', 'Financial Report Ready'), ('RESOURCE_ASSIGNED', 'Resource Assigned'), ('RESOURCE_TRANSFER', 'Resource Location Transferred')], default='GENERAL', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dms_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dms_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipient_groups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='recipient_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recipient_groups',
                'ordering': ['name'],
            },
        ),
    ]
