# Generated by Django 6.0.5 on 2026-09-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notification_recipientgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientgroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_activity_privilege',
            field=models.BooleanField(default=False, help_text='Grants privilege to create, edit, reschedule, and manage departmental activities.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_finance_balance_access',
            field=models.BooleanField(default=False, help_text='Grants privilege to view departmental balance and budget overview figures.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_finance_privilege',
            field=models.BooleanField(default=False, help_text='Grants privilege to create, edit, and submit finance requests.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_resource_privilege',
            field=models.BooleanField(default=False, help_text='Grants privilege to create, edit, and manage department resources and assets.'),
        ),
    ]
