# Generated by Django 6.0.5 on 2026-09-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_recipientgroup_is_active_alter_notification_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('GENERAL', 'General Notification'), ('ACTIVITY_INVITE', 'Activity Invitation'), ('ACTIVITY_UPDATE', 'Activity Update'), ('ACTIVITY_CANCEL', 'Activity Cancelled'), ('EXPENSE_SUBMITTED', 'Expense Submitted'), ('EXPENSE_APPROVED', 'Expense Approved'), ('EXPENSE_REJECTED', 'Expense Rejected'), ('REPORT_READY', 'Financial Report Ready'), ('REPORT_REJECTED', 'Financial Report Rejected'), ('ACTIVITY_SUBMITTED', 'Activity Submitted'), ('ACTIVITY_APPROVED', 'Activity Approved'), ('ACTIVITY_REJECTED', 'Activity Rejected'), ('RESOURCE_ASSIGNED', 'Resource Assigned'), ('RESOURCE_TRANSFER', 'Resource Location Transferred'), ('RESOURCE_BOOKING', 'Resource Booking'), ('RESOURCE_APPROVED', 'Resource Booking Approved'), ('RESOURCE_REJECTED', 'Resource Booking Rejected')], default='GENERAL', max_length=40),
        ),
    ]
